In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd

2022-01-12 09:25:21.290418: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-12 09:25:21.290438: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.6.0'

In [5]:
fork_model = tf.keras.models.load_model('/home/harny/Github/tff-app/2021-TBD2/models/scenario1/v0.0.10')

2022-01-12 09:25:30.112993: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-12 09:25:30.113019: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-12 09:25:30.113033: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (LuHa-X1C9): /proc/driver/nvidia/version does not exist
2022-01-12 09:25:30.113349: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
fork_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)          36928     
_________________________________________________________________
flatten (Flatten)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 64)                6

In [7]:
label = ['T-shirt', 'Trouser', 'Shirt', 'Dress', 'Ankle boot']
model = tf.keras.models.Sequential([
               tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
               tf.keras.layers.MaxPooling2D((2, 2)),
               tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
               tf.keras.layers.MaxPooling2D((2, 2)),
               tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
               tf.keras.layers.Flatten(),
               tf.keras.layers.Dense(64, activation='relu'),
               tf.keras.layers.Dense(len(label))])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)          36928     
_________________________________________________________________
flatten (Flatten)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 64)                6

In [14]:
for i in range(0, len(model.layers)-1):
    model.layers[i].trainable = False
for i in range(0, len(model.layers)):
    print(i, model.layers[i].trainable)

0 False
1 False
2 False
3 False
4 False
5 False
6 False
7 True


In [10]:
model.layers[0].trainable = False

In [105]:
ex = len(model.layers[-1].get_weights()[1])-len(fork_model.layers[-1].get_weights()[1])
for i in range(0, len(model.layers)-1):
    model.layers[i].set_weights(fork_model.layers[i].get_weights())
model.layers[-1].set_weights([np.pad(fork_model.layers[-1].get_weights()[0], (0, ex), mode='constant')[:-ex, :],
                              np.pad(fork_model.layers[-1].get_weights()[1], (0, ex), mode='constant')])

In [ ]:
model.layers[-1].get_weights()

In [ ]:
np.pad(fork_model.layers[-1].get_weights()[0], (0, 2), mode='constant')

In [85]:
np.pad(fork_model.layers[-1].get_weights()[0], (0, 2), mode='constant')[:-2, :].shape

(64, 5)

In [100]:
ex = len(model.layers[-1].get_weights()[1])-len(fork_model.layers[-1].get_weights()[1])
ex

2

In [101]:
np.pad(fork_model.layers[-1].get_weights()[0], (0, ex), mode='constant')[:-ex, :].shape

(64, 5)

In [104]:
model.layers[-1].set_weights([np.pad(fork_model.layers[-1].get_weights()[0], (0, ex), mode='constant')[:-ex, :],
                              np.pad(fork_model.layers[-1].get_weights()[1], (0, ex), mode='constant')])

In [ ]:
np.pad(model_b1.layers[1].get_weights()[1], (0, 1), mode='constant')]

In [79]:
model.layers[-1].get_weights()[0]

array([[-0.03016701,  0.24419457,  0.21055865,  0.07538   , -0.1846309 ],
       [ 0.16348624,  0.26852202,  0.15753612,  0.13691148, -0.164722  ],
       [ 0.14934078, -0.1405697 ,  0.11223575,  0.07744873, -0.04207817],
       [ 0.12009561, -0.20220631, -0.21989433,  0.2476157 ,  0.0203228 ],
       [ 0.18895227, -0.22782299, -0.0349299 ,  0.26182294,  0.06132641],
       [-0.07674526,  0.25788796, -0.20826231, -0.18260962,  0.11334729],
       [ 0.02744979,  0.06801757,  0.236785  ,  0.20511091,  0.11803162],
       [-0.01223165,  0.15129408, -0.07418774, -0.14206539, -0.08386582],
       [-0.20721573,  0.02279153, -0.21722537,  0.0741061 ,  0.2783668 ],
       [ 0.15642148, -0.21910332, -0.0350866 , -0.25556102, -0.02491608],
       [ 0.1941016 ,  0.12356871, -0.16109604, -0.27007383,  0.09860459],
       [ 0.1038163 , -0.14851172, -0.26477712, -0.00683773, -0.04329735],
       [-0.1658838 ,  0.17277285,  0.08027968,  0.00090188,  0.06777823],
       [ 0.04489645, -0.19340894, -0.1

In [80]:
model.layers[-1].get_weights()[0].shape

(64, 5)

In [62]:
model.layers[0].get_weights()[0]

array([[[[ 2.51954287e-01, -2.48611450e-01, -7.64121935e-02,
           8.15245416e-03,  4.33446690e-02,  1.19553521e-01,
           6.25601709e-02, -3.61519992e-01, -1.49119407e-01,
          -4.31703776e-02, -1.21812329e-01, -9.39898640e-02,
          -2.36974768e-02, -1.38829015e-02,  1.80491671e-01,
          -1.50463909e-01, -1.53730214e-01, -1.45984367e-01,
           6.78855553e-02,  1.15935072e-01, -2.92008650e-02,
          -4.91809845e-02, -4.94665727e-02, -2.21753716e-01,
           1.52740449e-01, -2.22560704e-01, -2.08120584e-01,
          -1.26269728e-01, -2.25882143e-01,  1.82497233e-01,
           9.53492671e-02, -2.84959041e-02],
         [ 3.64410393e-02, -1.27399310e-01,  7.74438083e-02,
          -1.92450844e-02,  1.19533435e-01,  8.47131312e-02,
          -7.68478662e-02, -3.45944464e-01, -2.49822557e-01,
           1.30944163e-01, -2.26981640e-01, -2.28197485e-01,
          -5.39799295e-02,  3.78291309e-02,  1.78385779e-01,
          -1.48051111e-02, -1.28990307e-

In [63]:
fork_model.layers[0].get_weights()[0][:24]

array([[[[ 2.51954287e-01, -2.48611450e-01, -7.64121935e-02,
           8.15245416e-03,  4.33446690e-02,  1.19553521e-01,
           6.25601709e-02, -3.61519992e-01, -1.49119407e-01,
          -4.31703776e-02, -1.21812329e-01, -9.39898640e-02,
          -2.36974768e-02, -1.38829015e-02,  1.80491671e-01,
          -1.50463909e-01, -1.53730214e-01, -1.45984367e-01,
           6.78855553e-02,  1.15935072e-01, -2.92008650e-02,
          -4.91809845e-02, -4.94665727e-02, -2.21753716e-01,
           1.52740449e-01, -2.22560704e-01, -2.08120584e-01,
          -1.26269728e-01, -2.25882143e-01,  1.82497233e-01,
           9.53492671e-02, -2.84959041e-02],
         [ 3.64410393e-02, -1.27399310e-01,  7.74438083e-02,
          -1.92450844e-02,  1.19533435e-01,  8.47131312e-02,
          -7.68478662e-02, -3.45944464e-01, -2.49822557e-01,
           1.30944163e-01, -2.26981640e-01, -2.28197485e-01,
          -5.39799295e-02,  3.78291309e-02,  1.78385779e-01,
          -1.48051111e-02, -1.28990307e-

In [27]:
model.get_weights()[9]

array([0., 0., 0., 0., 0.], dtype=float32)

In [28]:
fork_model.get_weights()[9]

array([-0.00943153, -0.09860183,  0.01667351], dtype=float32)

In [44]:
len(fork_model.get_weights()[9].reshape([-1]))

3

In [57]:
len(model.layers)

8

In [51]:
fork_model.layers

In [54]:
fork_model.layers[7].get_weights()

[array([[ 3.20891570e-03, -5.25975585e-01,  1.47467898e-03],
        [ 1.41946971e-01,  1.82712078e-01,  2.24056110e-01],
        [ 2.75620103e-01, -6.41794279e-02,  1.28192782e-01],
        [-5.00834081e-04,  5.25278337e-02, -2.22519740e-01],
        [ 1.79533452e-01,  1.41439497e-01, -8.02752376e-02],
        [ 1.33081079e-01, -2.53223211e-01,  1.10438652e-02],
        [-1.67640716e-01, -6.53868079e-01, -1.31487653e-01],
        [ 7.04118162e-02,  4.73585308e-01,  8.01896863e-03],
        [ 1.32050633e-01, -2.97601104e-01, -1.24331964e-02],
        [ 6.59615546e-02, -1.82862833e-01, -1.38303488e-01],
        [-3.94792669e-02,  1.81104064e-01, -2.58374393e-01],
        [ 1.31117180e-01, -2.96282172e-01, -1.01228550e-01],
        [-2.63325244e-01, -3.11466277e-01,  6.14460632e-02],
        [ 9.84093100e-02, -5.44777811e-01,  2.46981815e-01],
        [-2.84968942e-01,  3.13932180e-01, -3.34894240e-01],
        [ 2.25261092e-01, -3.27859491e-01, -4.59681153e-02],
        [-2.86271125e-01